workflows:
  ios:
    name: iOS Build with Fastlane
    environment:
      vars:
        LC_ALL: en_US.UTF-8
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          gem install bundler
          bundle install
      - name: Build and Deploy
        script: |
          bundle exec fastlane ios deploy
    artifacts:
      - build/ios/ipa/*.ipa
