workflows:
  ios:
    name: Build and test iOS app
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/iphoneos/Runner.app
