default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :beta do
    # Build the app using the default scheme "Runner"
    build_app(scheme: "Runner")

    # Upload the built app to TestFlight
    upload_to_testflight
  end

  desc "Custom lane"
  lane :custom_lane do
    # You can add custom commands here if needed
  end
end
